"use client";
import * as React from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Building2, Search, UserRound, UsersRound } from "lucide-react";
import { clientsApi } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/form-controls";
import { ErrorBanner, MetricCard, PageHeader, PaginationBar } from "@/components/crm/page-header";

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(value);
const date = (value?: string | null) => value ? new Intl.DateTimeFormat("pt-BR").format(new Date(value)) : "Nunca";
const statusLabel = { LEAD: "Lead", CUSTOMER: "Cliente", RECURRING: "Recorrente" } as const;
const recencyLabels: Record<string, string> = { never: "Nunca comprou", "0-30": "0–30 dias", "31-60": "31–60 dias", "61-90": "61–90 dias", "90+": "Mais de 90 dias" };

function Bars({ rows, onClick }: { rows: Array<{ label: string; value: number }>; onClick?: (label: string) => void }) {
  const max = Math.max(...rows.map((r) => r.value), 1);
  if (!rows.length) return <p className="py-8 text-center text-sm text-muted-foreground">Nenhum dado identificado.</p>;
  return <div className="space-y-2">{rows.slice(0, 10).map((row) => <button type="button" key={row.label} onClick={() => onClick?.(row.label)} className="group flex w-full items-center gap-3 text-xs"><span className="w-24 truncate text-left text-muted-foreground">{row.label}</span><span className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><span className="block h-full rounded-full bg-primary transition-all group-hover:bg-primary/80" style={{ width: `${Math.max(4, row.value / max * 100)}%` }} /></span><strong className="w-9 text-right">{row.value}</strong></button>)}</div>;
}

export function ClientsPage() {
  const [page, setPage] = React.useState(1); const [search, setSearch] = React.useState(""); const [status, setStatus] = React.useState(""); const [type, setType] = React.useState(""); const [state, setState] = React.useState(""); const [recency, setRecency] = React.useState("");
  React.useEffect(() => setPage(1), [search, status, type, state, recency]);
  const dashboard = useQuery({ queryKey: ["clients", "dashboard"], queryFn: clientsApi.dashboard });
  const list = useQuery({ queryKey: ["clients", { page, search, status, type, state, recency }], queryFn: () => clientsApi.list({ page, pageSize: 20, search: search || undefined, status: status || undefined, type: type || undefined, state: state || undefined, country: state ? "BR" : undefined, recency: recency || undefined }) });
  const d = dashboard.data;
  return <div className="space-y-5"><PageHeader title="Clientes" description="Visão geral da sua base comercial" />
    {(dashboard.error || list.error) && <ErrorBanner message="Não foi possível carregar a base de clientes." />}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><MetricCard label="Total da base" value={d?.total ?? 0} loading={dashboard.isLoading} onClick={() => setStatus("")} /><MetricCard label="Clientes" value={d?.customers ?? 0} loading={dashboard.isLoading} onClick={() => setStatus("CUSTOMER")} hint="1+ compra" /><MetricCard label="Leads" value={d?.leads ?? 0} loading={dashboard.isLoading} onClick={() => setStatus("LEAD")} /><MetricCard label="Recorrentes" value={d?.recurring ?? 0} loading={dashboard.isLoading} onClick={() => setStatus("RECURRING")} /><MetricCard label="Total comprado" value={money(d?.lifetimeValue ?? 0)} loading={dashboard.isLoading} /><MetricCard label="Ticket médio" value={money(d?.averageTicket ?? 0)} loading={dashboard.isLoading} /></div>
    <div className="grid gap-4 lg:grid-cols-3">{[["Perfil da base", d?.profile ?? [], (label: string) => setStatus(label === "Leads" ? "LEAD" : label === "1 compra" ? "CUSTOMER" : "RECURRING")], ["Localização da base", d?.location ?? [], undefined], ["Clientes por estado", d?.states ?? [], (label: string) => setState(label)]].map(([title, rows, click]) => <Card key={title as string}><CardContent className="p-4"><h2 className="mb-4 text-sm font-semibold">{title as string}</h2><Bars rows={rows as any} onClick={click as any} /></CardContent></Card>)}</div>
    <div className="grid gap-4 lg:grid-cols-3"><Card><CardContent className="p-4"><h2 className="mb-4 text-sm font-semibold">Recência da base</h2><Bars rows={(d?.recency ?? []).map((r) => ({ ...r, label: recencyLabels[r.label] ?? r.label }))} onClick={(label) => setRecency(Object.entries(recencyLabels).find(([, value]) => value === label)?.[0] ?? "")} /></CardContent></Card><Card><CardContent className="p-4"><h2 className="mb-4 text-sm font-semibold">Clientes fora do Brasil</h2><Bars rows={d?.countries ?? []} /></CardContent></Card><Card><CardContent className="p-4"><h2 className="mb-3 text-sm font-semibold">Qualidade da base</h2><div className="grid grid-cols-2 gap-2 text-sm">{[["Sem telefone", d?.quality.withoutPhone], ["Sem e-mail", d?.quality.withoutEmail], ["Sem localização", d?.quality.withoutLocation], ["Sem responsável", d?.quality.withoutOwner]].map(([label, value]) => <div key={label as string} className="rounded-lg bg-muted/50 p-3"><p className="text-xs text-muted-foreground">{label}</p><strong className="text-lg">{value ?? 0}</strong></div>)}</div></CardContent></Card></div>
    <Card><CardContent className="p-4"><div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9" placeholder="Buscar por nome, telefone, e-mail ou documento" /></div><Select value={status} onChange={(e) => setStatus(e.target.value)} className="lg:w-40"><option value="">Todos os status</option><option value="LEAD">Leads</option><option value="CUSTOMER">1 compra</option><option value="RECURRING">Recorrentes</option></Select><Select value={type} onChange={(e) => setType(e.target.value)} className="lg:w-40"><option value="">Pessoa e empresa</option><option value="PERSON">Pessoa</option><option value="COMPANY">Empresa</option></Select><Select value={recency} onChange={(e) => setRecency(e.target.value)} className="lg:w-44"><option value="">Toda recência</option>{Object.entries(recencyLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead className="border-y bg-muted/30 text-xs text-muted-foreground"><tr><th className="px-3 py-3 text-left">Cliente</th><th className="px-3 text-left">Status</th><th className="px-3 text-left">Localização</th><th className="px-3 text-left">Responsável</th><th className="px-3 text-right">Pedidos</th><th className="px-3 text-right">Total comprado</th><th className="px-3 text-left">Última compra</th><th className="px-3 text-left">Negociação</th></tr></thead><tbody>{list.data?.data.map((profile) => <tr key={profile.profileId} className="border-b hover:bg-muted/20"><td className="px-3 py-3"><Link className="flex items-center gap-2 font-medium hover:text-primary" href={`/clients/${encodeURIComponent(profile.profileId)}`}>{profile.profileType === "COMPANY" ? <Building2 className="h-4 w-4" /> : <UserRound className="h-4 w-4" />}<span><span className="block">{profile.name}</span><span className="block text-xs font-normal text-muted-foreground">{profile.email || profile.phone || "Sem contato"}</span></span></Link></td><td className="px-3"><Badge variant={profile.status === "RECURRING" ? "success" : profile.status === "CUSTOMER" ? "default" : "secondary"}>{statusLabel[profile.status]}</Badge></td><td className="px-3">{[profile.location.city, profile.location.state || profile.location.country].filter(Boolean).join(", ") || "—"}</td><td className="px-3">{profile.owner?.name || "Sem responsável"}</td><td className="px-3 text-right">{profile.orderCount}</td><td className="px-3 text-right font-medium">{money(profile.lifetimeValue)}</td><td className="px-3">{date(profile.lastPurchaseAt)}</td><td className="px-3">{profile.openDeals ? `${profile.openDeals} aberta(s)` : "—"}</td></tr>)}</tbody></table>{!list.isLoading && !list.data?.data.length && <div className="py-12 text-center"><UsersRound className="mx-auto mb-2 h-8 w-8 text-muted-foreground" /><p className="text-sm text-muted-foreground">Nenhum cliente encontrado com estes filtros.</p></div>}</div><PaginationBar page={page} totalPages={list.data?.meta.totalPages ?? 1} onPageChange={setPage} /></CardContent></Card>
  </div>;
}
