"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Building2, CalendarDays, Mail, MapPin, Phone, ShoppingBag, UserRound } from "lucide-react";
import { clientsApi } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { ErrorBanner, MetricCard } from "@/components/crm/page-header";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
const date = (value?: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(new Date(value)) : "—";
const statusLabel = { LEAD: "Lead", CUSTOMER: "Cliente", RECURRING: "Recorrente" } as const;

export function CustomerProfilePage({ profileId }: { profileId: string }) {
  const query = useQuery({ queryKey: ["clients", profileId], queryFn: () => clientsApi.get(profileId) });
  const profile = query.data;
  if (query.isLoading) return <div className="space-y-4"><div className="h-24 animate-pulse rounded-xl bg-muted" /><div className="h-72 animate-pulse rounded-xl bg-muted" /></div>;
  if (!profile) return <ErrorBanner message="Não foi possível carregar este cliente." />;
  return <div className="space-y-5"><Link href="/clients" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Voltar para Clientes</Link>
    <Card><CardContent className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary">{profile.profileType === "COMPANY" ? <Building2 /> : <UserRound />}</span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">{profile.name}</h1><Badge variant={profile.status === "RECURRING" ? "success" : profile.status === "CUSTOMER" ? "default" : "secondary"}>{statusLabel[profile.status]}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{profile.profileType === "COMPANY" ? "Conta comercial" : "Pessoa"} · Responsável: {profile.owner?.name || "Não atribuído"}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground">{profile.phone && <span className="flex items-center gap-1.5"><Phone className="h-4 w-4" />{profile.phone}</span>}{profile.email && <span className="flex items-center gap-1.5"><Mail className="h-4 w-4" />{profile.email}</span>}<span className="flex items-center gap-1.5"><MapPin className="h-4 w-4" />{[profile.location.city, profile.location.state, profile.location.country].filter(Boolean).join(", ") || "Sem localização"}</span></div></div></div><div className="flex flex-wrap gap-1">{profile.tags.map((tag) => <Badge key={tag.id} variant="outline">{tag.name}</Badge>)}</div></div></CardContent></Card>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MetricCard label="Total comprado" value={money(profile.lifetimeValue)} /><MetricCard label="Pedidos" value={profile.orderCount} /><MetricCard label="Ticket médio" value={money(profile.averageTicket)} /><MetricCard label="Primeira compra" value={date(profile.firstPurchaseAt)} /><MetricCard label="Última compra" value={date(profile.lastPurchaseAt)} /></div>
    <Tabs defaultValue="overview"><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="overview">Visão geral</TabsTrigger><TabsTrigger value="orders">Pedidos ({profile.orders.length})</TabsTrigger><TabsTrigger value="deals">Negócios ({profile.deals.length})</TabsTrigger><TabsTrigger value="tasks">Tarefas ({profile.tasks.length})</TabsTrigger><TabsTrigger value="notes">Notas ({profile.notes.length})</TabsTrigger><TabsTrigger value="timeline">Timeline</TabsTrigger></TabsList>
      <TabsContent value="overview"><div className="grid gap-4 lg:grid-cols-2"><Card><CardContent className="p-5"><h2 className="mb-4 font-semibold">Informações</h2><dl className="grid grid-cols-2 gap-4 text-sm"><Info label="Tipo" value={profile.profileType === "COMPANY" ? "Empresa" : "Pessoa"} /><Info label="Documento" value={profile.document || "—"} /><Info label="Origem" value={profile.source || "Não identificada"} /><Info label="Unidades compradas" value={String(profile.units)} /><Info label="Negociações abertas" value={String(profile.openDeals)} /><Info label="Responsável" value={profile.owner?.name || "Sem responsável"} /></dl></CardContent></Card><Card><CardContent className="p-5"><h2 className="mb-4 font-semibold">Endereço</h2><p className="flex items-start gap-2 text-sm"><MapPin className="mt-0.5 h-4 w-4 text-muted-foreground" />{[profile.location.address, profile.location.city, profile.location.state, profile.location.country].filter(Boolean).join(", ") || "Nenhuma localização identificada."}</p>{profile.profileType === "COMPANY" && <><h3 className="mb-2 mt-5 text-sm font-semibold">Contatos da empresa</h3><div className="space-y-2">{profile.contacts.map((contact) => <div key={contact.id} className="rounded-lg border p-3 text-sm"><strong>{contact.name}</strong><p className="text-xs text-muted-foreground">{contact.email || contact.phone || "Sem dados de contato"}</p></div>)}</div></>}</CardContent></Card></div></TabsContent>
      <TabsContent value="orders"><List empty="Nenhum pedido válido identificado.">{profile.orders.map((order) => <Link href={`/orders/${order.id}`} key={order.id} className="flex items-center justify-between rounded-lg border p-3 hover:border-primary/40"><span className="flex items-center gap-3"><ShoppingBag className="h-4 w-4 text-primary" /><span><strong>Pedido #{order.number}</strong><small className="block text-muted-foreground">{date(order.orderedAt)}</small></span></span><strong>{money(Number(order.finalValue ?? 0))}</strong></Link>)}</List></TabsContent>
      <TabsContent value="deals"><List empty="Nenhum negócio vinculado.">{profile.deals.map((deal) => <Link href={`/pipelines/${deal.pipelineId}?deal=${deal.id}`} key={deal.id} className="flex items-center justify-between rounded-lg border p-3 hover:border-primary/40"><span><strong>{deal.name}</strong><small className="block text-muted-foreground">{deal.pipeline?.name} · {deal.stage?.name}</small></span><Badge variant={deal.status === "OPEN" ? "default" : "secondary"}>{deal.status}</Badge></Link>)}</List></TabsContent>
      <TabsContent value="tasks"><List empty="Nenhuma tarefa vinculada.">{profile.tasks.map((task) => <Link href={`/tasks/${task.id}`} key={task.id} className="flex items-center justify-between rounded-lg border p-3 hover:border-primary/40"><span><strong>{task.title}</strong><small className="block text-muted-foreground">{task.assignee?.name || "Sem responsável"}</small></span><span className="text-xs text-muted-foreground">{date(task.dueAt)}</span></Link>)}</List></TabsContent>
      <TabsContent value="notes"><List empty="Nenhuma nota vinculada.">{profile.notes.map((note) => <div key={note.id} className="rounded-lg border p-3 text-sm"><p>{note.content}</p><small className="mt-2 block text-muted-foreground">{note.author?.name || "Sistema"} · {date(note.createdAt)}</small></div>)}</List></TabsContent>
      <TabsContent value="timeline"><List empty="Nenhuma atividade registrada.">{profile.activities.map((activity) => <div key={activity.id} className="flex gap-3 rounded-lg border p-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-muted"><CalendarDays className="h-4 w-4" /></span><div><strong className="text-sm">{activity.title}</strong><p className="text-sm text-muted-foreground">{activity.description}</p><small className="text-muted-foreground">{date(activity.createdAt)}</small></div></div>)}</List></TabsContent>
    </Tabs></div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
function List({ children, empty }: { children: React.ReactNode; empty: string }) { return <Card><CardContent className="space-y-2 p-4">{Array.isArray(children) && children.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">{empty}</p> : children}</CardContent></Card>; }
